### ISSUE TITLE
First attempt at Integrating sigrid

### ISSUE THREAD

**Issue by ngraymon** [ngraymon/termfactory#96]
[Github page here ](https://github.com/Software-Improvement-Group/sigridci)
Advice was to use the Alternative 2b: GitHub Marketplace for workflow instead of the Sigrid CI client script.

Also give feedback about any difficulties with documentation or using the GitHub workflow

**Comment by ngraymon** [comment]
To test that the workflows are setup correctly, we should be able to use the b version scripts from:
https://github.com/Software-Improvement-Group/sigridci/blob/main/docs/github-actions.md

But 
```
on:
  push:
    branches:
      - dev_sigrid
```

@lhprice  can you find out if we can specify the pull request like so?
```
on:
  pull_request:
    branches:
      - dev_sigrid
```
